CREATE DATABASE ESTACIONAMENTO;

USE ESTACIONAMENTO;

/* CREATE TABLES */

CREATE TABLE CARRO (
	
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	COR VARCHAR(20) NOT NULL,
	PLACA VARCHAR(10) NOT NULL
);


CREATE TABLE PROPRIETARIO(
	
	IDPROPRIETARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(15) UNIQUE,
	EMAIL VARCHAR(50) UNIQUE,
	SEXO ENUM('M','F'),
	ID_CARRO INT UNIQUE,
	FOREIGN KEY (ID_CARRO)
	REFERENCES CARRO (IDCARRO)
);


CREATE TABLE PAGAMENTOS(
	
	IDPAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,	
	TIPO ENUM('MENSAL' , 'DIARIA'),
	VALOR INT(10),
	ID_CARRO INT,
	FOREIGN KEY (ID_CARRO)
	REFERENCES CARRO (IDCARRO)
);

DESC PAGAMENTOS;


/* INSERT DE DADOS - TABELA CARRO */


INSERT INTO CARRO VALUES(NULL, 'GOL', 'VERMELHO', 'DWT-9853');
INSERT INTO CARRO VALUES(NULL, 'UNO', 'CINZA', 'EXV-9I60');
INSERT INTO CARRO VALUES(NULL, 'PÁLIO', 'PRATA', 'GTC-8415');

SELECT * FROM CARRO;


/* INSERT TABELA PROPRIETARIO */

INSERT INTO PROPRIETARIO VALUES(NULL, 'JOSÉ FERREIRA', '42165983006', 'JOSE@GMAIL.COM', 'M', 3);
INSERT INTO PROPRIETARIO VALUES(NULL, 'MARIA HELENA', '569874122039', 'MARIAH@GMAIL.COM', 'F', 1);
INSERT INTO PROPRIETARIO VALUES(NULL, 'FERNANDO RIBEIRO DOS SANTOS', '45298703690', 'FERNANDINHORS@HOTMAIL.COM', 'M', 2);


SELECT * FROM PROPRIETARIO;


/* INSERT TABELA PAGAMENTO */

INSERT INTO PAGAMENTOS VALUES(NULL, 'MENSAL', 150, 3);
INSERT INTO PAGAMENTOS VALUES(NULL, 'DIARIA', 20, 2);
INSERT INTO PAGAMENTOS VALUES(NULL, 'MENSAL', 150, 1);

SELECT * FROM PAGAMENTOS;


/* Inner Join COM 2 TABELAS E COM 3 TABELAS */

SELECT MODELO, PLACA, NOME, EMAIL
FROM CARRO
INNER JOIN PROPRIETARIO
ON IDCARRO = ID_CARRO;


SELECT C.MODELO, C.PLACA, P.NOME, P.EMAIL, PG.TIPO, PG.VALOR, C.IDCARRO
FROM CARRO C
INNER JOIN PROPRIETARIO P
ON C.IDCARRO = P.ID_CARRO
INNER JOIN PAGAMENTOS PG
ON C.IDCARRO = PG.ID_CARRO
WHERE SEXO = 'M';




	